--Pratica 4
--ex 2
CREATE OR REPLACE VIEW RELATORIO_NOTAS AS
  SELECT P.NROUSP, P.NOTAFINAL, ET.NOTA 
  FROM LBD10_PARTICIPANTE P, LBD14_ENTREGA_TRABALHO ET
  WHERE (ET.NOTA + P.NOTAFINAL) > 10;
  
select p.