all:
	javac -d WEB-INF/classes/ src/com/news/db/Config.java
	javac -d WEB-INF/classes/ -cp WEB-INF/classes/ src/com/news/db/DBConnection.java
	javac -d WEB-INF/classes/ -cp WEB-INF/classes/ src/com/news/project/News.java
