.TH uberkey 8 "October 8th, 2003"
.SH NAME
uberkey \- a keylogger
.SH SYNOPSIS
uberkey
.SH DESCRIPTION
uberkey directly reads keyboard input from the keyboard controller and
does a basic translation.
.SH BUGS
It might miss some keys, it won't log keys if you keep a key pressed.
.SH AUTHOR
.PP
Gürkan Sengün <gurkan@linuks.mine> is the author of uberkey.
