CLASSPATH=./WEB-INF/classes

all:
	javac -d ./WEB-INF/classes -cp $(CLASSPATH) src/com/news/db/Config.java
	javac -d ./WEB-INF/classes -cp $(CLASSPATH) src/com/news/db/DBConnection.java
	javac -d ./WEB-INF/classes -cp $(CLASSPATH) src/com/news/project/News.java
