--1.A
SELECT V1.NROUSP, COUNT(DISTINCT p1.CODCURSO) AS "Total de cursos"
FROM LBD01_VINCULO_USP v1 JOIN LBD10_PARTICIPANTE p1
  ON v1.nrousp = p1.nrousp
GROUP BY p1.nrousp
ORDER BY "Total de cursos";

--1.B
SELECT * FROM LBD01_VINCULO_USP WHERE 
EXTRACT(YEAR FROM TO_DATE(DATANASCIMENTO, 'DD-MM-RR'))  BETWEEN 1985 AND 1993
AND EXTRACT (MONTH FROM TO_DATE(DATANASCIMENTO, 'DD-MM-RR')) BETWEEN 09 AND 12;

--1.C
SELECT  P.NROUSP, T.CODCURSO, G.NROGRUPO, T.NROTRABALHO
FROM LBD13_TRABALHO T JOIN LBD11_GRUPO G
    ON T.CODCURSO = G.CODCURSO
JOIN LBD10_PARTICIPANTE P
    ON P.CODCURSO = T.CODCURSO
ORDER BY P.NROUSP;

--1.D
SELECT DISTINCT P.NROUSP, P.CODCURSO, G.NROGRUPO
FROM LBD10_PARTICIPANTE P, LBD11_GRUPO G
WHERE P.NROUSP NOT IN 
(SELECT M.NROUSP FROM LBD08_MATRICULA M JOIN LBD07_TURMA T
ON M.CODDISC = T.CODDISC)
AND P.CODCURSO IN(SELECT G.CODCURSO FROM LBD11_GRUPO G);

--1.E
CREATE SEQUENCE LBD_SEQ_NRO_MSG
MINVALUE 1 
MAXVALUE 999999 
INCREMENT BY 1 
START WITH 1 
NOCACHE 
NOORDER 
NOCYCLE ;

INSERT INTO lbd17_log_acesso
select LBD_SEQ_LOG_ACESSO.NEXTVAL, SYSDATE-(LBD_SEQ_LOG_ACESSO.CURRVAL*10),
       t1.nrousp, t1.codcurso, t2.nrorecurso
from lbd10_participante t1, lbd16_recurso_eletronico t2
where t1.codcurso = t2.codcurso;

INSERT INTO LBD18_MENSAGEM VALUES
(LBD_SEQ_NRO_MSG.NEXTVAL , 1, 1, 'DUVIDA','Estou com duvida em como usar o e-learning, alguem me ajuda?',SYSDATE);
INSERT INTO LBD18_MENSAGEM VALUES
(LBD_SEQ_NRO_MSG.NEXTVAL , 10, 3, 'DUVIDA','Estou com duvida em como usar o e-learning, alguem me ajuda?',SYSDATE);
INSERT INTO LBD18_MENSAGEM VALUES
(LBD_SEQ_NRO_MSG.NEXTVAL , 5, 5, 'MEMBRO PARA GRUPO','Ola pessoal, meu grupo está precisando de um integrante
quem estiver sem grupo, favor entrar em contato',SYSDATE);
INSERT INTO LBD18_MENSAGEM VALUES
(LBD_SEQ_NRO_MSG.NEXTVAL , 5, 3, '[Re:]MEMBRO PARA GRUPO','Estou sem grupo, gostaria de fazer parte do seu, retorne a 
mensagem em caso afirmativo',SYSDATE);
INSERT INTO LBD18_MENSAGEM VALUES
(LBD_SEQ_NRO_MSG.NEXTVAL , 5, 5, '[Re:]MEMBRO PARA GRUPO','Ok, está confirmado entao.',SYSDATE);

SELECT * FROM LBD01_VINCULO_USP V
WHERE EXISTS (SELECT NULL FROM LBD17_LOG_ACESSO LA
              WHERE V.NROUSP = LA.NROUSP)
AND 
      EXISTS (SELECT NULL FROM LBD18_MENSAGEM MSG
              WHERE V.NROUSP = MSG.NROUSP);

--1.F
SELECT (M.NOTA + P.NOTAFINAL)/2  MEDIA
FROM LBD08_MATRICULA m JOIN LBD09_CURSO_ELETRONICO ce
    ON M.CODDISC = CE.CODDISC AND M.ANO = CE.ANO AND M.NROTURMA = CE.NROTURMA
JOIN LBD10_PARTICIPANTE p
    ON CE.CODCURSO = P.CODCURSO;
--#################################################################################################
--2.A
(SELECT V.NROUSP, V.NOME, V.TIPOVINC, V.DATAINGRESSO, V.DATANASCIMENTO, V.ATIVO
--AL.IDADE, AL.CIDADENASC, AL.ESTADO, NULL NIVEL, NULL LOTACAO
FROM LBD01_VINCULO_USP V JOIN LBD03_ALUNO AL
ON V.NROUSP = AL.NROUSP

UNION 

SELECT V.NROUSP, V.NOME, V.TIPOVINC, V.DATAINGRESSO, V.DATANASCIMENTO, V.ATIVO
--NULL, NULL, NULL, F.NIVEL, F.LOTACAO
FROM LBD01_VINCULO_USP V JOIN LBD04_FUNCIONARIO F
ON V.NROUSP = F.NROUSP)

MINUS 

SELECT V.NROUSP, V.NOME, V.TIPOVINC, V.DATAINGRESSO, V.DATANASCIMENTO, V.ATIVO
--NULL, NULL, NULL, NULL, NULL
FROM LBD01_VINCULO_USP V JOIN LBD10_PARTICIPANTE P
ON V.NROUSP = P.NROUSP

ORDER BY NROUSP;
*****************************************************************************************
--2.A MAIS SIMPLES
SELECT V.NROUSP, V.NOME, V.TIPOVINC, V.DATAINGRESSO, V.DATANASCIMENTO, V.ATIVO
FROM LBD01_VINCULO_USP V
WHERE V.TIPOVINC <> 3

MINUS

SELECT V.NROUSP, V.NOME, V.TIPOVINC, V.DATAINGRESSO, V.DATANASCIMENTO, V.ATIVO
--NULL, NULL, NULL, NULL, NULL
FROM LBD01_VINCULO_USP V JOIN LBD10_PARTICIPANTE P
ON V.NROUSP = P.NROUSP

ORDER BY NROUSP;

--2.B
SELECT *
FROM LBD01_VINCULO_USP V 
	WHERE NOT EXISTS(SELECT NULL FROM LBD10_PARTICIPANTE P
					WHERE V.NROUSP = P.NROUSP)
AND V.TIPOVINC <> 3;
	
--2.C
SELECT *
FROM LBD01_VINCULO_USP V 
	WHERE V.NROUSP NOT IN 
		(SELECT V.NROUSP FROM LBD01_VINCULO_USP V, LBD10_PARTICIPANTE P
			WHERE V.NROUSP = P.NROUSP)
	AND V.TIPOVINC <> 3
ORDER BY NROUSP;

--*************************************************************************************************
--3
--GRANTS
GRANT INSERT (COD,NOME) ON LBD05_DISCIPLINA 
TO p5634966 WITH GRANT OPTION;

GRANT SELECT ON LBD05_DISCIPLINA
TO p5634966 WITH GRANT OPTION;

GRANT SELECT ON LBD03_ALUNO
TO p5634966 WITH GRANT OPTION;

--REVOKES
REVOKE INSERT ON LBD05_DISCIPLINA
FROM p5634966;

REVOKE SELECT ON LBD05_DISCIPLINA
FROM p5634966;

REVOKE SELECT ON LBD03_ALUNO
FROM p5634966;
