-- CRIANDO TIPO VINCULO USP
-- Objeto nao serah instanciado sozinho, mas deve ser derivavel para os subtipos
-- professor, aluno e funcionario
CREATE OR REPLACE TYPE P11_VINCULOUSP_TYPE AS OBJECT(

  NroUSP         NUMBER(7),
  TipoVinc       NUMBER(1),
  Nome           VARCHAR2(100),
  DataIngresso   DATE,
  DataNascimento DATE,
  Ativo          CHAR(1),
  MEMBER FUNCTION tempo_vinculo RETURN NUMBER  
) NOT FINAL ;
/


-- Criando o metodo tempo_vinculo associado aos objetos Tipo VinculoUSP
CREATE OR REPLACE TYPE BODY P11_VINCULOUSP_TYPE AS 
  MEMBER FUNCTION tempo_vinculo RETURN NUMBER IS
  
  BEGIN 

    RETURN TRUNC((SYSDATE - DataIngresso)/365);
  
  END tempo_vinculo;
  
END;
/

-- CRIANDO TIPO ALUNO
CREATE OR REPLACE TYPE P11_ALUNO_TYPE UNDER P11_VINCULOUSP_TYPE(

  Idade         NUMBER(2),
  CidadeNasc    VARCHAR2(50),
  Estado        VARCHAR(2),

  MEMBER PROCEDURE corrige_idade 
) FINAL;
/

-- Criando o metodo corrige_idade associado aos objetos Tipo Aluno
CREATE OR REPLACE TYPE BODY P11_ALUNO_TYPE AS 
  MEMBER PROCEDURE corrige_idade IS
  
  BEGIN 

    SELF.Idade := TRUNC((SYSDATE - SELF.DataNascimento)/365);
    
  END corrige_idade;
  
END;
/

-- CRIANDO TIPO PROFESSOR
CREATE OR REPLACE TYPE P11_PROF_TYPE UNDER P11_VINCULOUSP_TYPE(

  Titulacao     VARCHAR2(9),
  Predio        NUMBER(2),
  Sala          NUMBER(2),

  MEMBER FUNCTION localizacao RETURN VARCHAR2

) FINAL ;
/

-- Criando o metodo tempo_vinculo associado aos objetos Tipo Professor
CREATE OR REPLACE TYPE BODY P11_PROF_TYPE AS 
  MEMBER FUNCTION localizacao RETURN VARCHAR2 IS
  
  BEGIN 

    RETURN SELF.Predio||'-'||SELF.Sala;
  
  END localizacao;
  
END;
/

-- CRIANDO TIPO FUNCIONARIO
CREATE OR REPLACE TYPE P11_FUNC_TYPE UNDER P11_VINCULOUSP_TYPE(

  Nivel         VARCHAR2(8) ,
  Lotacao       VARCHAR2(5) 

) FINAL ;
/

--CRIANDO O TIPO DISCIPLINA
CREATE OR REPLACE TYPE P11_DISCIPLINA_TYPE AS OBJECT(

  Cod	  VARCHAR2(7),
  Nome   VARCHAR2(100)

) FINAL;
/

--CRIANDO O TIPO LECIONA
CREATE OR REPLACE TYPE P11_LECIONA_TYPE AS OBJECT(

  NroUSPProf Number(7),
  CodDisc VARCHAR2(7),

  NroUSPProfREF REF P11_PROF_TYPE,
  CodDiscREF REF P11_DISCIPLINA_TYPE

) FINAL;
/


--CRIANDO A TABELA PARA VINCULO USP A PARTIR DO OBJETO 
CREATE TABLE P11_VINCULOUSP OF P11_VINCULOUSP_TYPE(

  CONSTRAINT PK_P11_VINCULO_USP PRIMARY KEY (NroUSP),
  CONSTRAINT CK_P11_VINCULO_USP CHECK (TipoVinc IN (1, 2, 3)),
  CONSTRAINT CK_P11_ATIVO CHECK (Ativo IN ('y','n'))

);
/

--CRIANDO A TABELA PARA PROFESSOR A PARTIR DO OBJETO 
CREATE TABLE P11_PROFESSOR OF P11_PROF_TYPE(

  CONSTRAINT PK_P11_PROFESSOR PRIMARY KEY (NroUSP),
  CONSTRAINT FK_P11_PROFESSOR_NROUSP FOREIGN KEY (NroUSP)
     REFERENCES P11_VINCULOUSP (NroUSP) ON DELETE CASCADE,
  CONSTRAINT P11_CK_TITULACAO CHECK (Titulacao IN ('Mestrado','Doutorado'))

);
/

--CRIANDO A TABELA PARA ALUNO A PARTIR DO OBJETO 
CREATE TABLE P11_ALUNO OF P11_ALUNO_TYPE(

  CONSTRAINT P11_PK_ALUNO PRIMARY KEY (NroUSP),
  CONSTRAINT P11_FK_ALUNO_NROUSP FOREIGN KEY (NroUSP)
     REFERENCES P11_VINCULOUSP (NroUSP) ON DELETE CASCADE,
  CONSTRAINT P11_CK_IDADE CHECK (Idade > 10)

);
/
--CRIANDO A TABELA PARA FUNCIONARIO A PARTIR DO OBJETO 
CREATE TABLE P11_FUNC OF P11_FUNC_TYPE(

  CONSTRAINT P11_PK_FUNCIONARIO PRIMARY KEY (NroUSP),
  CONSTRAINT P11_FK_FUNCION_NROUSP FOREIGN KEY (NroUSP)
     REFERENCES P11_VINCULOUSP (NroUSP) ON DELETE CASCADE,
  CONSTRAINT P11_CK_NIVEL CHECK (Nivel IN ('Basico', 'Tecnico', 'Superior')),
  CONSTRAINT P11_CK_LOTACAO CHECK (Lotacao IN ('ICMC', 'EESC', 'IQSC', 'IFSC'))

);
/

--CRIANDO A TABELA PARA DISCIPLINA A PARTIR DO OBJETO 
CREATE TABLE P11_DISCIPLINA OF P11_DISCIPLINA_TYPE(

  CONSTRAINT P11_PK_DISCIPLINA PRIMARY KEY (Cod)

);
/


--CRIANDO A TABELA PARA LECIONA A PARTIR DO OBJETO 
CREATE TABLE P11_LECIONA OF P11_LECIONA_TYPE(

  CONSTRAINT P11_PK_LECIONA PRIMARY KEY (NroUSPProf, CodDisc),
  CONSTRAINT P11_FK_LECIONA_PROF FOREIGN KEY (NroUSPProf)
  	REFERENCES P11_PROFESSOR(NroUSP) ON DELETE CASCADE,
  CONSTRAINT P11_FK_LECIONA_DISC FOREIGN KEY (CodDisc)
  	REFERENCES P11_DISCIPLINA(Cod) ON DELETE CASCADE,

  NroUSPProfREF WITH ROWID REFERENCES P11_PROFESSOR,
  CodDiscREF WITH ROWID REFERENCES P11_DISCIPLINA

);


/*
DROP TABLE P11_ALUNO;
DROP TABLE P11_FUNC;
DROP TABLE P11_LECIONA;
DROP TABLE P11_DISCIPLINA;
DROP TABLE P11_PROFESSOR;
DROP TABLE P11_VINCULOUSP;

DROP TYPE P11_ALUNO_TYPE;
DROP TYPE P11_FUNC_TYPE;
DROP TYPE P11_LECIONA_TYPE;
DROP TYPE P11_PROF_TYPE;
DROP TYPE P11_DISCIPLINA_TYPE;
DROP TYPE P11_VINCULOUSP_TYPE;
*/