# Makefile para os teste do Analisador Lexico 
# Compiladores 2011 - Linguagem Frankie (Parte 1)
# Autor : Ubiratan Soares, Humberto Yagi, Ulisses Soares
# Data 30/03/2011


all:
	chmod +x compile.sh
	./compile.sh
	
tests:
	chmod +x tests.sh
	./tests.sh
	
clean :
	rm *.class
	rm *.java
	rm -rf Results