--Provavelmente gera erros

DROP TABLE LBD18_MENSAGEM CASCADE CONSTRAINTS;
DROP TABLE LBD17_LOG_ACESSO CASCADE CONSTRAINTS;
DROP TABLE LBD16_RECURSO_ELETRONICO CASCADE CONSTRAINTS;
DROP TABLE LBD15_TIPO_RECURSO CASCADE CONSTRAINTS;
DROP TABLE LBD14_ENTREGA_TRABALHO CASCADE CONSTRAINTS;
DROP TABLE LBD13_TRABALHO CASCADE CONSTRAINTS;
DROP TABLE LBD12_COMPOE_GRUPO CASCADE CONSTRAINTS;
DROP TABLE LBD11_GRUPO CASCADE CONSTRAINTS;
DROP TABLE LBD10_PARTICIPANTE CASCADE CONSTRAINTS;
DROP TABLE LBD09_CURSO_ELETRONICO CASCADE CONSTRAINTS;
DROP TABLE LBD08_MATRICULA CASCADE CONSTRAINTS;
DROP TABLE LBD07_TURMA CASCADE CONSTRAINTS;
DROP TABLE LBD06_LECIONA CASCADE CONSTRAINTS;
DROP TABLE LBD05_DISCIPLINA CASCADE CONSTRAINTS;
DROP TABLE LBD04_FUNCIONARIO;
DROP TABLE LBD03_ALUNO;
DROP TABLE LBD02_PROFESSOR;
DROP TABLE LBD01_VINCULO_USP CASCADE CONSTRAINTS; 


DROP SEQUENCE LBD_SEQ_LOG_ACESSO;
DROP SEQUENCE LBD_SEQ_NRO_USP;
DROP SEQUENCE LBD_SEQ_COD_CURSO;