CLASSPATH=./WEB-INF/classes

all:
	javac -d WEB-INF/classes -cp $(CLASSPATH) src/com/empresa/bd/Config.java
	javac -d WEB-INF/classes -cp $(CLASSPATH) src/com/empresa/bd/DBConnection.java
	javac -d WEB-INF/classes -cp $(CLASSPATH) src/com/empresa/projeto/User.java
